module.exports = ({ response }) => {
    /* response.writeHead(200, {
        'Content-Type': 'text/html'
    }); */
    response.end(`
<!DOCTYPE html>
<html>

<head>
    <title>test/sub</title>
</head>

<body>
    <h1>Generated by index.js!</h1>
</body>

</html>
`.trim()
    );
};
